cmake_minimum_required(VERSION 3.5)

project(03.homework)


add_executable(
        main
        main.cpp
        random_value.h
        random_value.cpp
        check_value.h
        check_value.cpp
        high_scores.h
        high_scores.cpp
        # argument.cpp
        # argument.h


)
